### ISSUE TITLE
get / set -OVP and S-OCP

### ISSUE THREAD

**Issue by HBerecz** [lambcutlet/DPS5005_pyGUI#15]
How can I get or set S-OVP (over-voltage) and S-OCP (over-current)?
In DPS3005 PC Software V1.3 is this possible (see attached file). But this program is not very good.

[DPS3005-PC-Software.zip](https://github.com/lambcutlet/DPS5005_pyGUI/files/2472476/DPS3005-PC-Software.zip)

**Comment by lambcutlet** [comment]
To view these values perform `python dps_modbus.py` then `r` with an enter. All the values stored in the dps unit is displayed.
note: you may need to adjust the comport on line 240 `ser = Serial_modbus('/dev/ttyUSB0', 1, 9600, 8)` for a connection.

to adjust s-ovp & s-ocp:

1. type `sovp` enter or type `socp` enter 
2. type value enter
3. type `r` enter to read the values

otherwise you can manually change the values via the 'set' button on the power supply.

**Comment by HBerecz** [comment]
In windows the command line 'python dps_modbus.py r' does not function to display all the values stored in the dps unit.
Line 240 is 'self.open_CSV(self.CSV_file)'. Do I really have to change it?

**Comment by HBerecz** [comment]
Sorry, that was a mistake, instead of dps_modbus.py I started dps_GUI_program.py.
But when I start dps_modbus.py, I get the error message:
Traceback (most recent call last):
  File "D:\DPS3005-py\dps_modbus.py", line 225, in <module>
    route = raw_input("Enter command: ")
NameError: name 'raw_input' is not defined
